<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class InteractionResource extends JsonResource {
    public function toArray(Request $request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
